# Generated by Django 5.2 on 2025-05-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_booked_by_event_description_ar_event_name_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='event_images/'),
        ),
    ]
