# Generated by Django 5.2 on 2025-05-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='event_images/{pk}.png'),
        ),
    ]
